---
name: Super-Linter

on:
  push: null
  pull_request: null

jobs:
  build:
    name: Lint code base
    runs-on: ubuntu-latest
    permissions:
     contents: read
     packages: read
     statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: master  # Ganti ke 'master' jika repositori menggunakan branch default 'master'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
